server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: Trannguyenvy0966272357
    url: jdbc:mysql://localhost:3306/shopmedb
    username: TranNguyenVy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  
  security:
    oauth2:
      client:
        registration:
           google:
              client-id: 631955864223-irplipi194bheiht5vqitma6fsmgbs9i.apps.googleusercontent.com
              client-secret: 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
              scope:
                  - email
                  - profile
           facebook:
              client-id: 1139092167437716
              client-secret: 545b31cd692f41765ec61ccd2c91bc0a
              scope:
                  - email
                  - public_profile     
          
          
          